
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - client-ms_app-network
    restart: always

networks:
  client-ms_app-network:
    external: true